document.getElementById('loginButton').addEventListener('click',function(){
    window.location.href='login.html';
});
document.getElementById('Signupbutton').addEventListener('click',function(){
    window.location.href='signup.html';
});
document.getElementById('backbutton').addEventListener('click',function(){
    window.location.href='landingpage.html';
});